# Generated by Django 4.2.30 on 2026-06-03 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pantryitem',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pantry_items', to='recipes.ingredient'),
        ),
        migrations.AlterUniqueTogether(
            name='pantryitem',
            unique_together={('ingredient', 'location')},
        ),
    ]
