# Generated by Django 4.2.30 on 2026-06-04 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0005_pantryitem_fk_and_unique'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pantryitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='pantryitem',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pantry_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recipe',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='pantryitem',
            unique_together={('ingredient', 'location', 'owner')},
        ),
    ]
